import { Metadata } from "next"
import { GruposClient } from "./client"

export const metadata: Metadata = {
  title: "Grupos",
}

// Mock data
const grupos = [
  {
    id: "1",
    codigo: "B1-MJ-001",
    nombre: "Ingles B1 - Martes y Jueves",
    curso: "Ingles General B1",
    idioma: "Ingles",
    nivel: "B1",
    profesor: "Maria Garcia",
    sede: "Tenerife Centro",
    aula: "Aula 3",
    tipo: "REGULAR",
    modalidad: "PRESENCIAL",
    horario: "18:00 - 19:30",
    diasSemana: ["Martes", "Jueves"],
    fechaInicio: "2025-09-15",
    fechaFin: "2026-06-30",
    estado: "EN_CURSO",
    plazasMax: 12,
    plazasOcupadas: 10,
    asistenciaMedia: 88,
  },
  {
    id: "2",
    codigo: "A2-LMV-002",
    nombre: "Ingles A2 - Lunes, Miercoles, Viernes",
    curso: "Ingles General A2",
    idioma: "Ingles",
    nivel: "A2",
    profesor: "Carlos Lopez",
    sede: "Tenerife Centro",
    aula: "Aula 1",
    tipo: "INTENSIVO",
    modalidad: "PRESENCIAL",
    horario: "10:30 - 12:00",
    diasSemana: ["Lunes", "Miercoles", "Viernes"],
    fechaInicio: "2025-10-01",
    fechaFin: "2026-03-31",
    estado: "EN_CURSO",
    plazasMax: 10,
    plazasOcupadas: 8,
    asistenciaMedia: 92,
  },
  {
    id: "3",
    codigo: "C1-SS-003",
    nombre: "Ingles C1 - Sabados",
    curso: "Ingles Avanzado C1",
    idioma: "Ingles",
    nivel: "C1",
    profesor: "Ana Martinez",
    sede: "Tenerife Centro",
    aula: "Aula 5",
    tipo: "REGULAR",
    modalidad: "HIBRIDO",
    horario: "10:00 - 13:00",
    diasSemana: ["Sabado"],
    fechaInicio: "2025-09-20",
    fechaFin: "2026-06-15",
    estado: "EN_CURSO",
    plazasMax: 8,
    plazasOcupadas: 6,
    asistenciaMedia: 85,
  },
  {
    id: "4",
    codigo: "B2-MJ-004",
    nombre: "Ingles B2 - Martes y Jueves",
    curso: "Ingles General B2",
    idioma: "Ingles",
    nivel: "B2",
    profesor: "Pedro Sanchez",
    sede: "Las Palmas",
    aula: "Aula 2",
    tipo: "REGULAR",
    modalidad: "PRESENCIAL",
    horario: "16:00 - 17:30",
    diasSemana: ["Martes", "Jueves"],
    fechaInicio: "2025-09-15",
    fechaFin: "2026-06-30",
    estado: "EN_CURSO",
    plazasMax: 12,
    plazasOcupadas: 9,
    asistenciaMedia: 82,
  },
  {
    id: "5",
    codigo: "A1-LMV-005",
    nombre: "Ingles A1 - Tardes",
    curso: "Ingles Iniciacion A1",
    idioma: "Ingles",
    nivel: "A1",
    profesor: "Laura Fernandez",
    sede: "Tenerife Centro",
    aula: "Aula 4",
    tipo: "REGULAR",
    modalidad: "PRESENCIAL",
    horario: "18:00 - 19:30",
    diasSemana: ["Lunes", "Miercoles", "Viernes"],
    fechaInicio: "2025-10-15",
    fechaFin: "2026-06-30",
    estado: "EN_CURSO",
    plazasMax: 15,
    plazasOcupadas: 12,
    asistenciaMedia: 90,
  },
  {
    id: "6",
    codigo: "A1-DE-001",
    nombre: "Aleman A1 - Principiantes",
    curso: "Aleman Iniciacion A1",
    idioma: "Aleman",
    nivel: "A1",
    profesor: "Hans Mueller",
    sede: "Tenerife Centro",
    aula: "Aula 6",
    tipo: "REGULAR",
    modalidad: "PRESENCIAL",
    horario: "19:00 - 20:30",
    diasSemana: ["Martes", "Jueves"],
    fechaInicio: "2025-10-01",
    fechaFin: "2026-06-30",
    estado: "EN_CURSO",
    plazasMax: 10,
    plazasOcupadas: 7,
    asistenciaMedia: 95,
  },
  {
    id: "7",
    codigo: "A2-FR-002",
    nombre: "Frances A2 - Mananas",
    curso: "Frances General A2",
    idioma: "Frances",
    nivel: "A2",
    profesor: "Sophie Martin",
    sede: "Las Palmas",
    aula: "Aula 3",
    tipo: "REGULAR",
    modalidad: "ONLINE",
    horario: "09:00 - 10:30",
    diasSemana: ["Lunes", "Miercoles"],
    fechaInicio: "2025-09-15",
    fechaFin: "2026-06-30",
    estado: "EN_CURSO",
    plazasMax: 12,
    plazasOcupadas: 5,
    asistenciaMedia: 88,
  },
  {
    id: "8",
    codigo: "B1-EMP-001",
    nombre: "Ingles Empresas - Tech Solutions",
    curso: "Ingles Business B1",
    idioma: "Ingles",
    nivel: "B1",
    profesor: "Maria Garcia",
    sede: "In-Company",
    aula: "Oficinas Cliente",
    tipo: "EMPRESA",
    modalidad: "PRESENCIAL",
    horario: "13:00 - 14:30",
    diasSemana: ["Martes", "Jueves"],
    fechaInicio: "2025-11-01",
    fechaFin: "2026-04-30",
    estado: "EN_CURSO",
    plazasMax: 8,
    plazasOcupadas: 8,
    asistenciaMedia: 78,
  },
]

export default function GruposPage() {
  return <GruposClient grupos={grupos} />
}
