import { Metadata } from "next"
import { PipelineClient } from "./client"

export const metadata: Metadata = {
  title: "Pipeline Comercial",
}

// Mock data
const leads = [
  {
    id: "1",
    nombre: "Carlos Rodriguez",
    empresa: null,
    email: "carlos@email.com",
    telefono: "+34 612 345 678",
    estado: "NUEVO",
    temperatura: "CALIENTE",
    score: 85,
    idiomaInteres: "Ingles",
    valorEstimado: 1200,
    comercial: "Maria Garcia",
    proximoContacto: "2026-01-04",
  },
  {
    id: "2",
    nombre: "Tech Solutions SL",
    empresa: "Tech Solutions SL",
    email: "rrhh@techsolutions.es",
    telefono: "+34 623 456 789",
    estado: "CONTACTADO",
    temperatura: "TIBIO",
    score: 65,
    idiomaInteres: "Ingles",
    valorEstimado: 8500,
    comercial: "Pedro Sanchez",
    proximoContacto: "2026-01-05",
  },
  {
    id: "3",
    nombre: "Miguel Garcia",
    empresa: null,
    email: "miguel@gmail.com",
    telefono: "+34 634 567 890",
    estado: "TEST_REALIZADO",
    temperatura: "MUY_CALIENTE",
    score: 92,
    idiomaInteres: "Aleman",
    valorEstimado: 980,
    comercial: "Maria Garcia",
    proximoContacto: "2026-01-03",
  },
  {
    id: "4",
    nombre: "Laura Martinez",
    empresa: null,
    email: "laura@hotmail.com",
    telefono: "+34 645 678 901",
    estado: "PROPUESTA_ENVIADA",
    temperatura: "CALIENTE",
    score: 78,
    idiomaInteres: "Ingles",
    valorEstimado: 1450,
    comercial: "Carlos Lopez",
    proximoContacto: "2026-01-06",
  },
  {
    id: "5",
    nombre: "Innovate Corp",
    empresa: "Innovate Corp",
    email: "formacion@innovate.com",
    telefono: "+34 656 789 012",
    estado: "NEGOCIACION",
    temperatura: "MUY_CALIENTE",
    score: 95,
    idiomaInteres: "Frances",
    valorEstimado: 15000,
    comercial: "Pedro Sanchez",
    proximoContacto: "2026-01-04",
  },
  {
    id: "6",
    nombre: "Elena Fernandez",
    empresa: null,
    email: "elena@gmail.com",
    telefono: "+34 667 890 123",
    estado: "NUEVO",
    temperatura: "FRIO",
    score: 35,
    idiomaInteres: "Ingles",
    valorEstimado: 890,
    comercial: null,
    proximoContacto: null,
  },
  {
    id: "7",
    nombre: "Pablo Diaz",
    empresa: null,
    email: "pablo@outlook.com",
    telefono: "+34 678 901 234",
    estado: "CONTACTADO",
    temperatura: "TIBIO",
    score: 55,
    idiomaInteres: "Espanol",
    valorEstimado: 750,
    comercial: "Maria Garcia",
    proximoContacto: "2026-01-07",
  },
  {
    id: "8",
    nombre: "Global Services",
    empresa: "Global Services SA",
    email: "info@globalservices.es",
    telefono: "+34 689 012 345",
    estado: "PROPUESTA_ENVIADA",
    temperatura: "CALIENTE",
    score: 82,
    idiomaInteres: "Ingles",
    valorEstimado: 12000,
    comercial: "Carlos Lopez",
    proximoContacto: "2026-01-05",
  },
  {
    id: "9",
    nombre: "Ana Ruiz",
    empresa: null,
    email: "ana.ruiz@email.com",
    telefono: "+34 690 123 456",
    estado: "TEST_REALIZADO",
    temperatura: "CALIENTE",
    score: 75,
    idiomaInteres: "Ingles",
    valorEstimado: 1100,
    comercial: "Maria Garcia",
    proximoContacto: "2026-01-04",
  },
  {
    id: "10",
    nombre: "Consulting Plus",
    empresa: "Consulting Plus",
    email: "hr@consultingplus.es",
    telefono: "+34 601 234 567",
    estado: "NEGOCIACION",
    temperatura: "MUY_CALIENTE",
    score: 88,
    idiomaInteres: "Ingles",
    valorEstimado: 9500,
    comercial: "Pedro Sanchez",
    proximoContacto: "2026-01-03",
  },
]

export default function PipelinePage() {
  return <PipelineClient leads={leads} />
}
