import { Metadata } from "next"
import { LeadsClient } from "./client"

export const metadata: Metadata = {
  title: "Leads",
}

// Mock data - en produccion vendria de la base de datos
const leads = [
  {
    id: "1",
    nombre: "Carlos",
    apellidos: "Rodriguez Martinez",
    email: "carlos.rodriguez@email.com",
    telefono: "+34 612 345 678",
    segmento: "ADULTO_PARTICULAR",
    origen: "WEB_ORGANICO",
    estado: "NUEVO",
    temperatura: "CALIENTE",
    score: 85,
    idiomaInteres: "Ingles",
    nivelDetectado: "B1",
    comercial: "Maria Garcia",
    createdAt: "2026-01-02T10:30:00",
  },
  {
    id: "2",
    nombre: "Ana",
    apellidos: "Lopez Fernandez",
    email: "ana.lopez@empresa.com",
    telefono: "+34 623 456 789",
    segmento: "EMPRESA",
    origen: "GOOGLE_ADS",
    estado: "CONTACTADO",
    temperatura: "TIBIO",
    score: 65,
    idiomaInteres: "Ingles",
    nivelDetectado: "A2",
    comercial: "Pedro Sanchez",
    createdAt: "2026-01-01T15:45:00",
  },
  {
    id: "3",
    nombre: "Miguel",
    apellidos: "Garcia Perez",
    email: "miguel.garcia@gmail.com",
    telefono: "+34 634 567 890",
    segmento: "ADULTO_PARTICULAR",
    origen: "REFERIDO",
    estado: "TEST_REALIZADO",
    temperatura: "MUY_CALIENTE",
    score: 92,
    idiomaInteres: "Aleman",
    nivelDetectado: "A1",
    comercial: "Maria Garcia",
    createdAt: "2025-12-28T09:15:00",
  },
  {
    id: "4",
    nombre: "Laura",
    apellidos: "Martinez Ruiz",
    email: "laura.m@hotmail.com",
    telefono: "+34 645 678 901",
    segmento: "NINO_PARTICULAR",
    origen: "COLEGIO",
    estado: "PROPUESTA_ENVIADA",
    temperatura: "CALIENTE",
    score: 78,
    idiomaInteres: "Ingles",
    nivelDetectado: null,
    comercial: "Carlos Lopez",
    createdAt: "2025-12-27T11:00:00",
  },
  {
    id: "5",
    nombre: "David",
    apellidos: "Sanchez Gomez",
    email: "david.sanchez@empresa.es",
    telefono: "+34 656 789 012",
    segmento: "EMPRESA",
    origen: "META_ADS",
    estado: "NEGOCIACION",
    temperatura: "MUY_CALIENTE",
    score: 95,
    idiomaInteres: "Frances",
    nivelDetectado: "B2",
    comercial: "Pedro Sanchez",
    createdAt: "2025-12-20T14:30:00",
  },
  {
    id: "6",
    nombre: "Elena",
    apellidos: "Fernandez Torres",
    email: "elena.ft@gmail.com",
    telefono: "+34 667 890 123",
    segmento: "ADULTO_PARTICULAR",
    origen: "LLAMADA_ENTRANTE",
    estado: "NUEVO",
    temperatura: "FRIO",
    score: 35,
    idiomaInteres: "Ingles",
    nivelDetectado: null,
    comercial: null,
    createdAt: "2026-01-03T08:00:00",
  },
  {
    id: "7",
    nombre: "Pablo",
    apellidos: "Diaz Moreno",
    email: "pablo.diaz@outlook.com",
    telefono: "+34 678 901 234",
    segmento: "ERASMUS",
    origen: "WEB_ORGANICO",
    estado: "CONTACTADO",
    temperatura: "TIBIO",
    score: 55,
    idiomaInteres: "Espanol",
    nivelDetectado: "A2",
    comercial: "Maria Garcia",
    createdAt: "2025-12-30T16:20:00",
  },
  {
    id: "8",
    nombre: "Sofia",
    apellidos: "Ruiz Navarro",
    email: "sofia.ruiz@empresa.com",
    telefono: "+34 689 012 345",
    segmento: "EMPRESA",
    origen: "EVENTO",
    estado: "MATRICULADO",
    temperatura: "MUY_CALIENTE",
    score: 100,
    idiomaInteres: "Ingles",
    nivelDetectado: "C1",
    comercial: "Carlos Lopez",
    createdAt: "2025-12-15T10:00:00",
  },
]

export default function LeadsPage() {
  return <LeadsClient leads={leads} />
}
